### ISSUE TITLE
the version does not work ae2stuff-extended-1.12.2-v0.8-0.2.jar on the server

### ISSUE THREAD

**Issue by DanChannel** [beecupbe/ae2stuff_extended#2]
the version does not work ae2stuff-extended-1.12.2-v0.8-0.2.jar on the server
не работает версия ae2stuff-extended-1.12.2-v0.8-0.2.jar на сервере

**Comment by beecupbe** [comment]
пофикшено в v0.2.1 - https://github.com/beecupbe/ae2stuff_extended/releases/tag/v0.2.1
